name: Deploy

on:
  push:
   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  # The type of runner to use

    steps:
      - name: Checkout repository  # Step to checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js  # Step to setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies  # Step to install npm dependencies
        run: npm install

      - name: Run tests  # Step to run tests
        run: npm test
      - name: Build static file
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
